### PR TITLE
Parse embedded CSS stylesheets

### PR DESCRIPTION
**Pull request by adozenlines**
Includes latest version of boost source

### CODE REVIEW

**Comment by micahpearlman** [comment]
Is there a reason the pull request has been closed?  I was planning on looking at it this week.  Looked like a great addition.

**Comment by adozenlines** [comment]
Hi Sorry about that it contained a few private documents i had to remove will create a new request as soon as i can...

**Comment by micahpearlman** [comment]
Absolutely, no problem.  Let me know if you need anything from me.

**Comment by adozenlines** [comment]
Plus on checkout the test project doesn’t because some of the boost headers are missing mainly “config.hpp” so i just dumped the entire boost files from the website into the boost framework folder for the build to be successful.

**Comment by adozenlines** [comment]
"doesn’t build" … This changes uses this https://github.com/adozenlines/stylesheet <https://github.com/adozenlines/stylesheet> project to accomplish the parsing all i did was bring these two projects together …

Sean.

**Pull request closed without merging**
